spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  session:
    jdbc:
      initialize-schema: never
      table-name: SPRING_SESSION
    timeout: 1440m
  sql:
    init:
      mode: never
  ai:
    mcp:
      client:
        enabled: true
        type: SYNC # or ASYNC
        name: "ai-tool-chat"
        # Spring Cloud Bindings library will automatically map the 
        # VCAP_SERVICES credentials to these properties at runtime.